### ISSUE TITLE
Discussion - Templating model inside ns4kafka

### ISSUE THREAD

**Issue by twobeeb** [michelin/ns4kafka#11]
Before starting implementation, it's important to discuss the scope and limits of ns4kafka.
I believe there are enough templating tools available on the market and templating should be done within the projects CI/CD scripts and not inside ns4kafka

Still, the idea is interesting, and this is how it would look like if implemented in ns4kafka : 

````yaml
apiVersion: v1
kind: ConnectorTemplate
metadata:
  name: JdbcSink_template
spec:
  connector.class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasks.max: 1
  topics: $TOPICS
  table.name.format: $TABLE
  connection.url: jdbc:thin:oracle:localhost:1521/DB
  connection.user: user
  connection.password: password
  db.timezone: "Europe/Paris"
  pk.mode: record_value
  insert.mode: upsert
  auto.evolve: false
  errors.tolerance: all
  errors.log.enable: true
  errors.log.include.messages: true
  errors.deadletterqueue.topic.name: $DLQ_TOPIC
  errors.deadletterqueue.context.headers.enable: true
  consumer.override.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="password";
---
apiVersion: v1
kind: ConnectorTemplateInstance
metadata:
  name: JdbcSink_topic1
spec:
  template_name: JdbcSink_template
  vars:
    TOPICS: topic1
    DLQ_TOPIC: sink-topic1-dlq
    TABLE: table1
  config:
    auto.evolve: true # overriden from template
    pk.fields: "Pk_Field1,Pk_Field2" # defined

````
