### ISSUE TITLE
Remove requirement to add "name" to kafka connect configs

### ISSUE THREAD

**Issue by twobeeb** [michelin/ns4kafka#150]
Today, Kafka Connect deployments must repeat the name in the config level even if it's already defined at the metadata level.

````yaml
---
apiVersion: v1
kind: Connector
metadata:
  name: project1.test # Once here
  namespace: project1
spec:
  connectCluster: local
  config:
    name: project1.test # <- Once more here
    connector.class: io.confluent.connect.jdbc.JdbcSinkConnector
    tasks.max: '1'
    ...
````
This is not user friendly, can lead to errors, and so it should be modified.
