### ISSUE TITLE
Kafkactl CLI : Implement a diff on resources

### ISSUE THREAD

**Issue by seb63110** [michelin/ns4kafka#17]
Provide a CLI command:

kafkactl diff -f "folder/file" 

to compare existing resources and local resources.

For topics, acls and connectords.

**Comment by twobeeb** [comment]
Requires #14 first
Proposed implementation details for MVP1

> For each yaml document in -f option :  
> - GET the resource on ns4kafka API
> - Compare  ``spec`` attribute with current document ``spec``
>    - Handle inner Maps (see configs attribute in example below)
> - Ignore ``metadata`` and ``status`` for now
> - Return the diff 

Example resource (single yaml document) :  
````yaml
---
apiVersion: v1
kind: Topic
metadata:
  name: priv_f4m_demo1
spec:
  replicationFactor: 3
  partitions: 3
  configs:
    min.insync.replicas: '2'
    cleanup.policy: delete,compact
    retention.bytes: '10000000'
````

If current object in ns4kafka looks like this :  
````json
{
        "apiVersion": "v1",
        "kind": "Topic",
        "metadata": {
            "name": "priv_f4m_demo1",
            "namespace": "f4m",
            "cluster": "local",
            "generation": 1,
            "creationTimestamp": "2021-03-15T12:35:16.035+00:00"
        },
        "spec": {
            "replicationFactor": 3,
            "partitions": 3,
            "configs": {
                "cleanup.policy": "delete",
                "retention.ms": "60000",
                "min.insync.replicas": "2"
            }
        },
        "status": {
            "phase": "Success",
            "message": "Topic created",
            "lastUpdateTime": "2021-03-15T12:35:16.035+00:00"
        }
````

the diff should ouput (formatting TBD):  
````
Changes detected (3) : 
ADD : configs.retention.bytes: '10000000'
MOD : configs.cleanup.policy: delete,compact
DEL : configs.retention.ms: '60000'
````

At some point later, we'll want the local yaml to be "applied" on ns4kafka in dry-run mode in order to validate the object as well
