### ISSUE TITLE
Handle multi-endpoints Kafka connect configurations

### ISSUE THREAD

**Issue by damienfayet** [michelin/ns4kafka#180]
When adding kafka connect workers, we can only specify one url.

Most of the time we need it to be able to handle at least 2 Urls in order to handle multi-node connect workers. (when the first one is not available anymore, request have to sent tto the next one in the list.

Change that : 
```
connects:
      - name: connectWorkerName
        url: "https://myUrl1:8083"
        username: user
        password: pass
```
to
```
connects:
      - name: connectWorkerName
        url: "https://myUrl1:8083","https://myUrl2:8083"
        username: user
        password: pass
```
