### ISSUE TITLE
Add possibility to create Kafka Connect Workers as a resource of a namespace

### ISSUE THREAD

**Issue by damienfayet** [michelin/ns4kafka#202]
Hello,

Now more and more projects are creating K8S based Connect Workers.

Adding new worker in Configmap requires a pod restart. It's not something we want. We would like projects/namespaces to be autonomous and add the possibility for each namespace to deploy new worker the same way they do for each resource.

i.e. 
```
---
apiVersion: v1
kind: ConnectWorker
metadata:
  name: test.test-connect
spec:
  config:
    name: test.test-connect
    url: "http://myworkerURL.com/"
    username: <username>
    password: <password>
```

We have to analyse before : 

- the impact on the synchronisation of configurations (how to handle an invalid conf or not responding worker.
- ensure there is no global impact in case of unavailability
