### ISSUE TITLE
Add aes256 vaulting capability for Kafka Connect Cluster

### ISSUE THREAD

**Issue by yraffin** [michelin/ns4kafka#226]
As Kafka Connect Cluster can be defined and managed as Ns4Kafka resource, we can update the spec to add the **aes256Key**, **aes256Salt** and **aes256Format** parameters in order to allow members of a namespace to generate the aes256 encrypted values for there connector configuration.

The connect cluster will need to use the following config provider to be able to decrypt the configuration:
[aes256 config provider](https://github.com/michelin/michelin-connect-plugins/blob/main/doc/config-providers/aes256-config-provider.md)

**Mandatory fields** :
- aes256Key
- aes256Salt

Default format is: `${dollar}{aes256:%s}`

Exemple with default format:
```yml
---
apiVersion: v1
kind: ConnectCluster
metadata:
  name: test.myConnectCluster
spec:
  url: http://localhost:8083
  username: myUsername
  password: myPassword
  aes256Key: aaaabbbbccccdddd
  aes256Salt: p8t42EhY9z2eSUdpGeq7HX7RboMrsJAhUnu3EEJJVS
---
```

Exemple with specific format:
```yml
apiVersion: v1
kind: ConnectCluster
metadata:
  name: test.myConnectCluster
spec:
  url: http://localhost:8083
  username: myUsername
  password: myPassword
  aes256Key: aaaabbbbccccdddd
  aes256Salt: p8t42EhY9z2eSUdpGeq7HX7RboMrsJAhUnu3EEJJVS
  aes256Format: "%s"
```
