### ISSUE TITLE
Quota management

### ISSUE THREAD

**Issue by twobeeb** [michelin/ns4kafka#25]
Quota management should follow k8s principles :
````yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: ns-project-1
  name: quota-1
spec:
  count/topics: "200" # maximum number of topics allowed on this namespace
  count/partitions: "400"
  disk/topics: "10Gi" # maximum size of all topics on this namespace (sum of retention.bytes for each partitions)
  count/connects: "100"
````
an "Admission controller" equivalent must be in charge of validating quota before apply and updating quota usage on apply/delete
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/admission_control_resource_quota.md
