### ISSUE TITLE
Namespace Controller

### ISSUE THREAD

**Issue by twobeeb** [michelin/ns4kafka#28]
Controller should be accessible by admin only and have the following functions
- list
- apply
- delete

````yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: project1
  cluster: local
spec:
  defaulKafkatUser: project1
  diskQuota: 0
  topicValidator:
    validationConstraints:
      min.insync.replicas:
        validation-type: Range
        min: 2
        max: 2
      retention.ms:
        validation-type: Range
        min: 60000
        max: 60480000
      partitions:
        validation-type: Range
        min: 3
        max: 6
      replication.factor:
        validation-type: Range
        min: 3
        max: 3
      cleanup.policy:
        validation-type: ValidList
        validStrings:
        - delete
        - compact
  connectValidator:
    validationConstraints:
      key.converter:
        validation-type: NonEmptyString
      value.converter:
        validation-type: NonEmptyString
      connector.class:
        validation-type: ValidString
        validStrings:
        - io.confluent.connect.jdbc.JdbcSourceConnector
        - io.confluent.connect.jdbc.JdbcSinkConnector
        - com.splunk.kafka.connect.SplunkSinkConnector
        - org.apache.kafka.connect.file.FileStreamSinkConnector
    sourceValidationConstraints:
      producer.override.sasl.jaas.config:
        validation-type: NonEmptyString
    sinkValidationConstraints:
      consumer.override.sasl.jaas.config:
        validation-type: NonEmptyString
    classValidationConstraints:
      io.confluent.connect.jdbc.JdbcSinkConnector:
        db.timezone:
          validation-type: NonEmptyString
````
