### ISSUE TITLE
Handle Confluent Cloud tags

### ISSUE THREAD

**Issue by loicgreffier** [michelin/ns4kafka#282]
Ns4Kafka should provide the ability to tag resources (topics and schemas) with Confluent Cloud tags: https://docs.confluent.io/cloud/current/api.html#tag/Types-(v1)/operation/createTagDefs.

### Users

Users should be able to tag their resources (schemas and topics) when deployed on Confluent Cloud only. The main solution is adding a new field in the resource metadata that contains all the tags split by a comma:

```yaml
---
apiVersion: v1
kind: Topic
metadata:
  name: myPrefix.topic
  tags: tag1,tag2,tag3
spec:
...
```

The list of possible tags for a namespace should be defined by admins, and validated at namespace level:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: myNamespace
  cluster: myCluster
  labels:
    contacts: namespace.owner@example.com
spec:
  topicValidator:
  connectValidator:
  tagValidator:
      tags:
        validation-type: ValidString
        validStrings:
          - tag1
          - tag2
          - tag3
```

A dedicated executor for tags might need to be implemented to handle both schema tags and topic tags.

### Admin

Tags might need to be declared in the Confluent Cloud before getting attached to a resource. In this case, 3 possible solutions:

- Tags might be created beforehand outside of Ns4Kafka (like Confluent Cloud service accounts).
- Tags might be created by admins from Ns4Kafka by running such kind of command: _kafkactl apply -f tag.yml_. In this case, a new admin resource might be created:

```yaml
---
apiVersion: v1
kind: Tag
metadata:
  name: tag1
spec:
  description: This is a wondeful tag
```

_This option may not make sens in Ns4Kafka as it is unrelated to namespaces at this point._

- Tags are created in Confluent Cloud at the first time a user links it to one of its resource.
