### ISSUE TITLE
InMemory AuthenticationProvider

### ISSUE THREAD

**Issue by twobeeb** [michelin/ns4kafka#33]
## Context
Currently ns4kafka supports Gitlab Authentication as well as all AuthenticationProviders available with Micronaut (LDAP, OIDC, ...)

Having the users defined within configuration is not supported.
This would be a great addition to demonstrate the features of ns4kafka without the need to configure Gitlab or LDAP.

## Proposition 

Create a new class InMemoryAuthenticationProvider that implements AuthenticationProvider interface and generate the UserDetails based on values defined in application.yaml
````yaml
micronaut:
  security:
    in-memory:
      enabled: true
      users: 
      - name: admin
        password: '$2y$13$jxGxc ... IuqDju', 
        groups: ['admin-group', 'group1']
      - name: user
        password: '$2y$13$jxGxc ... IuqDju', 
        groups: ['user-group', 'group2']   
````
