### ISSUE TITLE
question : how to handle "per environment" clusters ?

### ISSUE THREAD

**Issue by piif** [michelin/ns4kafka#431]
We handle several clusters, in different environments (dev, staging, production) and we have a question about CI/CD in such context :
ns4kafka is able to handle namespaces related to different clusters, but namespace names must be unique.
Thus, if I want to deliver "myNamespace" topics in my development cluster, and topics in another "myNamespace" for production cluster, how should I do ?
Is it better to use one ns4kafka server per environment, or should I prefix namespaces name by environment name ?

**Comment by loicgreffier** [comment]
@piif 

> Thus, if I want to deliver "myNamespace" topics in my development cluster, and topics in another "myNamespace" for production cluster, how should I do

You can manage different contexts using kafkactl:

```yml
kafkactl:
  contexts:
    - name: dev
      context:
        api: https://ns4kafka-dev-api.domain.com
        user-token: my_gitlab_token
        namespace: my_namespace
    - name: staging
      context:
        api: https://ns4kafka-dev-api.domain.com
        user-token: my_gitlab_token
        namespace: my_namespace
    - name: production
      context:
        api: https://ns4kafka-prod-api.domain.com
        user-token: my_gitlab_token
        namespace: my_namespace
```

and set your CI/CD jobs on the desired context before running actions:

```bash
kafkactl config use-context dev
```
