### ISSUE TITLE
A public ACL (grantedTo: *) is shown on all the clusters during a get acl

### ISSUE THREAD

**Issue by AlexisSouquiere** [michelin/ns4kafka#483]
## Describe the bug
When managing multiple clusters, if I create an ACL (for a CONNECT_CLUSTER in my case) with `grantedTo: "*"` on cluster1, I can see this ACL on a namespace on cluster2

## To Reproduce
- Setup ns4kafka to manage 2 clusters
- Create an ACL with `grantedTo: "*"` on ns1 on cluster1
- Do a `kafkactl get acl` on ns2 on cluster2
- The ACL is shown

## Expected behavior
This ACL should be visible only for the namespaces on cluster1

## Environment
- Kafkactl distribution and version: jar - version 1.12.1

If known:
- Ns4Kafka version: v1.12.0

## Additional context
ACL file
```yaml
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: acl-for-all-on-cluster1
  namespace: nsCluster1
spec:
  resourceType: CONNECT_CLUSTER
  resource: cc-cluster1
  resourcePatternType: LITERAL
  permission: WRITE
  grantedTo: "*"
```

Get acl output
```
java -jar kafkactl-1.12.1.jar get acl -n otherNsCluster1
ACL                               GRANTED_BY    GRANTED_TO    TYPE             RESOURCE          PATTERN   PERMISSION  AGE
acl-for-all-on-cluster1           nsCluster1    *             CONNECT_CLUSTER  cc-cluster1       LITERAL   WRITE       3 hours ago
acl-for-all-on-cluster2           nsCluster2    *             CONNECT_CLUSTER  cc-cluster2       LITERAL   WRITE       3 hours ago
acl-for-all-on-cluster3           nsCluster3    *             CONNECT_CLUSTER  cc-cluster3       LITERAL   WRITE       3 hours ago
```
