### ISSUE TITLE
Ignore case on authorization when comparing Gitlab groups

### ISSUE THREAD

**Issue by AlexisSouquiere** [michelin/ns4kafka#520]
## Problem
Suppose that I have a Gitlab group /group/mygroup
And the RoleBinding definition for a namespace ns1
```yaml
  subject:
    subjectType: GROUP
    subjectName: /group/myGroup
```

User gets `Access control entry failed because accessing forbidden namespace "ns1" (403).`

After updating the subjectName to `/group/mygroup`, you can access his namespace

## Suggestion
Ignore case during the authorization check

## Alternatives Considered
N/A
